"""Auto-generated curated menu. DO NOT EDIT BY HAND.
Run scripts/generate_preset_catalogs.py to regenerate.

Menu: bedroom_keeper  (room_type=bedroom, philosophy=keeper)
Shared by both presets of this philosophy (variant 0 and variant 1).
Sub_categories curated in menus.py; geometry from curated_manifest.json;
pricing carried from hero_catalog.py."""
from __future__ import annotations

from app.domain.catalog.model import CatalogItem
from app.schemas.state import Dimensions, RoomType

CATALOG: dict[str, CatalogItem] = {
    "bed_queen": CatalogItem(
        sku="BEDROOM-KEEPER-BED_QUEEN",
        asset_url="sh3d/blendswap_cc_by_lettocloud.glb",
        name_en="Queen Bed",
        name_hi="क्वीन बेड",
        category="sleeping",
        sub_category="bed_queen",
        rooms=[RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1889, height_mm=788, depth_mm=2165),
        price_inr=32000,
        build_price_inr=20000,
        materials=['wood_engineered', 'fabric'],
        tags=['bed', 'sleeping', 'queen', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bed_king": CatalogItem(
        sku="BEDROOM-KEEPER-BED_KING",
        asset_url="sh3d/blendswap_cc_by_lettocloud.glb",
        name_en="King Bed",
        name_hi="किंग बेड",
        category="sleeping",
        sub_category="bed_king",
        rooms=[RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1889, height_mm=788, depth_mm=2165),
        price_inr=42000,
        build_price_inr=26000,
        materials=['wood_engineered', 'fabric'],
        tags=['bed', 'sleeping', 'king', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "side_table": CatalogItem(
        sku="BEDROOM-KEEPER-SIDE_TABLE",
        asset_url="sh3d/blendswap_cc_0_bedsidetable2.glb",
        name_en="Side Table with Drawer",
        name_hi="साइड टेबल",
        category="table",
        sub_category="side_table",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=486, height_mm=454, depth_mm=481),
        price_inr=4500,
        build_price_inr=2900,
        materials=['wood_teak'],
        tags=['table', 'side_table', 'nightstand', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "wardrobe": CatalogItem(
        sku="BEDROOM-KEEPER-WARDROBE",
        asset_url="sh3d/blendswap_cc_by_wardrobe.glb",
        name_en="Two-door Wardrobe",
        name_hi="अलमारी",
        category="storage",
        sub_category="wardrobe",
        rooms=[RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=921, height_mm=2000, depth_mm=680),
        price_inr=34000,
        build_price_inr=21000,
        materials=['wood_engineered', 'laminate'],
        tags=['storage', 'wardrobe', 'closet', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.65,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "chest": CatalogItem(
        sku="BEDROOM-KEEPER-CHEST",
        asset_url="sh3d/blendswap_cc_by_chest.glb",
        name_en="Chest of Drawers",
        name_hi="दराज़ की अलमारी",
        category="storage",
        sub_category="chest",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1435, height_mm=820, depth_mm=536),
        price_inr=16500,
        build_price_inr=10500,
        materials=['wood_engineered'],
        tags=['storage', 'drawers', 'chest', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "cabinet": CatalogItem(
        sku="BEDROOM-KEEPER-CABINET",
        asset_url="sh3d/katorlegaz_filing_cabinet.glb",
        name_en="Storage Cabinet",
        name_hi="अलमारी",
        category="storage",
        sub_category="cabinet",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=386, height_mm=600, depth_mm=526),
        price_inr=13500,
        build_price_inr=8500,
        materials=['wood_engineered', 'laminate'],
        tags=['storage', 'cabinet', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bookshelf": CatalogItem(
        sku="BEDROOM-KEEPER-BOOKSHELF",
        asset_url="sh3d/contributions_meublehifihaut.glb",
        name_en="Open Bookshelf",
        name_hi="किताबों की अलमारी",
        category="storage",
        sub_category="bookshelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1559, height_mm=1830, depth_mm=414),
        price_inr=18000,
        build_price_inr=11500,
        materials=['wood_engineered'],
        tags=['storage', 'bookshelf', 'display', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "dressing_table": CatalogItem(
        sku="BEDROOM-KEEPER-DRESSING_TABLE",
        asset_url="sh3d/scopia_dressing_table.glb",
        name_en="Dressing Table with Mirror",
        name_hi="ड्रेसिंग टेबल",
        category="storage",
        sub_category="dressing_table",
        rooms=[RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=857, height_mm=1359, depth_mm=465),
        price_inr=19000,
        build_price_inr=12000,
        materials=['wood_engineered', 'glass'],
        tags=['dressing', 'vanity', 'bedroom', 'storage', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=700,
        placement_type="floor",
    ),
    "floating_shelf": CatalogItem(
        sku="BEDROOM-KEEPER-FLOATING_SHELF",
        asset_url="sh3d/lucapresidente_mensolaciliegio.glb",
        name_en="Floating Wall Shelf",
        name_hi="फ्लोटिंग शेल्फ",
        category="storage",
        sub_category="floating_shelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1020, height_mm=340, depth_mm=200),
        price_inr=4500,
        build_price_inr=2800,
        materials=['wood_engineered'],
        tags=['shelf', 'storage', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "bench": CatalogItem(
        sku="BEDROOM-KEEPER-BENCH",
        asset_url="sh3d/blendswap_cc_0_bench.glb",
        name_en="Upholstered Bench",
        name_hi="गद्देदार बेंच",
        category="seating",
        sub_category="bench",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1701, height_mm=508, depth_mm=459),
        price_inr=8000,
        build_price_inr=5000,
        materials=['fabric', 'wood_frame'],
        tags=['bench', 'seating', 'entry', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.85,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "accent_chair": CatalogItem(
        sku="BEDROOM-KEEPER-ACCENT_CHAIR",
        asset_url="sh3d/scopia_armchair2.glb",
        name_en="Accent Chair",
        name_hi="उच्चारण कुर्सी",
        category="seating",
        sub_category="accent_chair",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=728, height_mm=970, depth_mm=812),
        price_inr=9000,
        build_price_inr=5800,
        materials=['fabric', 'wood_frame'],
        tags=['chair', 'seating', 'accent', 'formal', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.8,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "lamp": CatalogItem(
        sku="BEDROOM-KEEPER-LAMP",
        asset_url="sh3d/contributions_lampehalogene.glb",
        name_en="Floor Lamp",
        name_hi="फ़र्श लैंप",
        category="lighting",
        sub_category="lamp",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=313, height_mm=1800, depth_mm=689),
        price_inr=4500,
        build_price_inr=None,
        materials=['metal', 'fabric_shade'],
        tags=['lighting', 'floor_lamp', 'ambient', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.5,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "desk_lamp": CatalogItem(
        sku="BEDROOM-KEEPER-DESK_LAMP",
        asset_url="sh3d/scopia_desk_lamp2.glb",
        name_en="Task Desk Lamp",
        name_hi="डेस्क लैंप",
        category="lighting",
        sub_category="desk_lamp",
        rooms=[RoomType.STUDY, RoomType.BEDROOM, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=225, height_mm=400, depth_mm=417),
        price_inr=2200,
        build_price_inr=None,
        materials=['metal'],
        tags=['lighting', 'desk_lamp', 'task', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.4,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "mirror": CatalogItem(
        sku="BEDROOM-KEEPER-MIRROR",
        asset_url="sh3d/contributions_mirror.glb",
        name_en="Wall Mirror",
        name_hi="दीवार दर्पण",
        category="decor",
        sub_category="mirror",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=400, height_mm=400, depth_mm=5),
        price_inr=3500,
        build_price_inr=None,
        materials=['glass', 'wood_frame'],
        tags=['mirror', 'decor', 'wall_mounted', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.1,
        front_clearance_mm=600,
        placement_type="wall",
    ),
    "wall_art": CatalogItem(
        sku="BEDROOM-KEEPER-WALL_ART",
        asset_url="sh3d/contributions_frame3verticalsummerphotos.glb",
        name_en="Framed Wall Art",
        name_hi="दीवार चित्र",
        category="decor",
        sub_category="wall_art",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=525, height_mm=254, depth_mm=30),
        price_inr=4500,
        build_price_inr=None,
        materials=['paper', 'wood_frame'],
        tags=['art', 'decor', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "rug": CatalogItem(
        sku="BEDROOM-KEEPER-RUG",
        asset_url="sh3d/katorlegaz_oriental_rug.glb",
        name_en="Hand-Knotted Rug",
        name_hi="कालीन",
        category="decor",
        sub_category="rug",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1858, height_mm=25, depth_mm=2577),
        price_inr=14000,
        build_price_inr=None,
        materials=['wool'],
        tags=['rug', 'decor', 'floor', 'anchor', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.95,
        front_clearance_mm=0,
        placement_type="floor",
    ),
}
