"""Auto-generated curated menu. DO NOT EDIT BY HAND.
Run scripts/generate_preset_catalogs.py to regenerate.

Menu: bedroom_breath  (room_type=bedroom, philosophy=breath)
Shared by both presets of this philosophy (variant 0 and variant 1).
Sub_categories curated in menus.py; geometry from curated_manifest.json;
pricing carried from hero_catalog.py."""
from __future__ import annotations

from app.domain.catalog.model import CatalogItem
from app.schemas.state import Dimensions, RoomType

CATALOG: dict[str, CatalogItem] = {
    "bed_queen": CatalogItem(
        sku="BEDROOM-BREATH-BED_QUEEN",
        asset_url="sh3d/contributions_lit.glb",
        name_en="Queen Bed",
        name_hi="क्वीन बेड",
        category="sleeping",
        sub_category="bed_queen",
        rooms=[RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1672, height_mm=785, depth_mm=2201),
        price_inr=32000,
        build_price_inr=20000,
        materials=['wood_engineered', 'fabric'],
        tags=['bed', 'sleeping', 'queen', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bed_king": CatalogItem(
        sku="BEDROOM-BREATH-BED_KING",
        asset_url="sh3d/blendswap_cc_0_bedwithtexture.glb",
        name_en="King Bed",
        name_hi="किंग बेड",
        category="sleeping",
        sub_category="bed_king",
        rooms=[RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1980, height_mm=765, depth_mm=2264),
        price_inr=42000,
        build_price_inr=26000,
        materials=['wood_engineered', 'fabric'],
        tags=['bed', 'sleeping', 'king', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "side_table": CatalogItem(
        sku="BEDROOM-BREATH-SIDE_TABLE",
        asset_url="sh3d/lucapresidente_comodinoazzurro.glb",
        name_en="Side Table with Drawer",
        name_hi="साइड टेबल",
        category="table",
        sub_category="side_table",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=500, height_mm=480, depth_mm=425),
        price_inr=4500,
        build_price_inr=2900,
        materials=['wood_teak'],
        tags=['table', 'side_table', 'nightstand', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "wardrobe": CatalogItem(
        sku="BEDROOM-BREATH-WARDROBE",
        asset_url="sh3d/lucapresidente_mobileazzurro.glb",
        name_en="Two-door Wardrobe",
        name_hi="अलमारी",
        category="storage",
        sub_category="wardrobe",
        rooms=[RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1000, height_mm=2400, depth_mm=570),
        price_inr=34000,
        build_price_inr=21000,
        materials=['wood_engineered', 'laminate'],
        tags=['storage', 'wardrobe', 'closet', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.65,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "accent_chair": CatalogItem(
        sku="BEDROOM-BREATH-ACCENT_CHAIR",
        asset_url="sh3d/scopia_armchair.glb",
        name_en="Accent Chair",
        name_hi="उच्चारण कुर्सी",
        category="seating",
        sub_category="accent_chair",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=788, height_mm=1001, depth_mm=777),
        price_inr=9000,
        build_price_inr=5800,
        materials=['fabric', 'wood_frame'],
        tags=['chair', 'seating', 'accent', 'formal', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.8,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "lamp": CatalogItem(
        sku="BEDROOM-BREATH-LAMP",
        asset_url="sh3d/contributions_lampehalogene.glb",
        name_en="Floor Lamp",
        name_hi="फ़र्श लैंप",
        category="lighting",
        sub_category="lamp",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=313, height_mm=1800, depth_mm=689),
        price_inr=4500,
        build_price_inr=None,
        materials=['metal', 'fabric_shade'],
        tags=['lighting', 'floor_lamp', 'ambient', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.5,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "desk_lamp": CatalogItem(
        sku="BEDROOM-BREATH-DESK_LAMP",
        asset_url="sh3d/scopia_desk_lamp1.glb",
        name_en="Task Desk Lamp",
        name_hi="डेस्क लैंप",
        category="lighting",
        sub_category="desk_lamp",
        rooms=[RoomType.STUDY, RoomType.BEDROOM, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=137, height_mm=450, depth_mm=342),
        price_inr=2200,
        build_price_inr=None,
        materials=['metal'],
        tags=['lighting', 'desk_lamp', 'task', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.4,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "mirror": CatalogItem(
        sku="BEDROOM-BREATH-MIRROR",
        asset_url="sh3d/contributions_rectangularmirror.glb",
        name_en="Wall Mirror",
        name_hi="दीवार दर्पण",
        category="decor",
        sub_category="mirror",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=500, height_mm=700, depth_mm=10),
        price_inr=3500,
        build_price_inr=None,
        materials=['glass', 'wood_frame'],
        tags=['mirror', 'decor', 'wall_mounted', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.1,
        front_clearance_mm=600,
        placement_type="wall",
    ),
    "wall_art": CatalogItem(
        sku="BEDROOM-BREATH-WALL_ART",
        asset_url="sh3d/scopia_frame2.glb",
        name_en="Framed Wall Art",
        name_hi="दीवार चित्र",
        category="decor",
        sub_category="wall_art",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=145, height_mm=199, depth_mm=145),
        price_inr=4500,
        build_price_inr=None,
        materials=['paper', 'wood_frame'],
        tags=['art', 'decor', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "rug": CatalogItem(
        sku="BEDROOM-BREATH-RUG",
        asset_url="sh3d/katorlegaz_oriental_rug.glb",
        name_en="Hand-Knotted Rug",
        name_hi="कालीन",
        category="decor",
        sub_category="rug",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1858, height_mm=25, depth_mm=2577),
        price_inr=14000,
        build_price_inr=None,
        materials=['wool'],
        tags=['rug', 'decor', 'floor', 'anchor', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.95,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "plant": CatalogItem(
        sku="BEDROOM-BREATH-PLANT",
        asset_url="sh3d/scopia_ficus.glb",
        name_en="Potted Floor Plant",
        name_hi="पौधा",
        category="decor",
        sub_category="plant",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=425, height_mm=824, depth_mm=415),
        price_inr=2800,
        build_price_inr=None,
        materials=['ceramic', 'foliage'],
        tags=['plant', 'decor', 'softness', 'prana', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.9,
        front_clearance_mm=200,
        placement_type="floor",
    ),
}
