"""Auto-generated curated menu. DO NOT EDIT BY HAND.
Run scripts/generate_preset_catalogs.py to regenerate.

Menu: dining_keeper  (room_type=dining, philosophy=keeper)
Shared by both presets of this philosophy (variant 0 and variant 1).
Sub_categories curated in menus.py; geometry from curated_manifest.json;
pricing carried from hero_catalog.py."""
from __future__ import annotations

from app.domain.catalog.model import CatalogItem
from app.schemas.state import Dimensions, RoomType

CATALOG: dict[str, CatalogItem] = {
    "dining_table": CatalogItem(
        sku="DINING-KEEPER-DINING_TABLE",
        asset_url="sh3d/scopia_table4.glb",
        name_en="4-Seater Dining Table",
        name_hi="चार-सीट डाइनिंग टेबल",
        category="table",
        sub_category="dining_table",
        rooms=[RoomType.LIVING, RoomType.DINING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1400, height_mm=750, depth_mm=900),
        price_inr=22000,
        build_price_inr=14000,
        materials=['wood_teak'],
        tags=['dining_table', 'table', 'dining', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=800,
        placement_type="floor",
    ),
    "dining_chair": CatalogItem(
        sku="DINING-KEEPER-DINING_CHAIR",
        asset_url="sh3d/blendswap_cc_by_ella_chair_f.glb",
        name_en="Dining Chair",
        name_hi="डाइनिंग कुर्सी",
        category="seating",
        sub_category="dining_chair",
        rooms=[RoomType.LIVING, RoomType.DINING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=460, height_mm=920, depth_mm=570),
        price_inr=4500,
        build_price_inr=2800,
        materials=['wood_teak', 'fabric'],
        tags=['chair', 'dining_chair', 'dining', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bench": CatalogItem(
        sku="DINING-KEEPER-BENCH",
        asset_url="sh3d/blendswap_cc_0_bench.glb",
        name_en="Upholstered Bench",
        name_hi="गद्देदार बेंच",
        category="seating",
        sub_category="bench",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1701, height_mm=508, depth_mm=459),
        price_inr=8000,
        build_price_inr=5000,
        materials=['fabric', 'wood_frame'],
        tags=['bench', 'seating', 'entry', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.85,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "sideboard": CatalogItem(
        sku="DINING-KEEPER-SIDEBOARD",
        asset_url="sh3d/lucapresidente_credenza.glb",
        name_en="Sideboard / Buffet",
        name_hi="साइडबोर्ड",
        category="storage",
        sub_category="sideboard",
        rooms=[RoomType.LIVING, RoomType.DINING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1660, height_mm=780, depth_mm=500),
        price_inr=16000,
        build_price_inr=10000,
        materials=['wood_engineered', 'laminate'],
        tags=['sideboard', 'buffet', 'storage', 'dining', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.65,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "cabinet": CatalogItem(
        sku="DINING-KEEPER-CABINET",
        asset_url="sh3d/katorlegaz_filing_cabinet.glb",
        name_en="Storage Cabinet",
        name_hi="अलमारी",
        category="storage",
        sub_category="cabinet",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=386, height_mm=600, depth_mm=526),
        price_inr=13500,
        build_price_inr=8500,
        materials=['wood_engineered', 'laminate'],
        tags=['storage', 'cabinet', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bookshelf": CatalogItem(
        sku="DINING-KEEPER-BOOKSHELF",
        asset_url="sh3d/contributions_meublehifihaut.glb",
        name_en="Open Bookshelf",
        name_hi="किताबों की अलमारी",
        category="storage",
        sub_category="bookshelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1559, height_mm=1830, depth_mm=414),
        price_inr=18000,
        build_price_inr=11500,
        materials=['wood_engineered'],
        tags=['storage', 'bookshelf', 'display', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "chest": CatalogItem(
        sku="DINING-KEEPER-CHEST",
        asset_url="sh3d/blendswap_cc_by_chest.glb",
        name_en="Chest of Drawers",
        name_hi="दराज़ की अलमारी",
        category="storage",
        sub_category="chest",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1435, height_mm=820, depth_mm=536),
        price_inr=16500,
        build_price_inr=10500,
        materials=['wood_engineered'],
        tags=['storage', 'drawers', 'chest', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "floating_shelf": CatalogItem(
        sku="DINING-KEEPER-FLOATING_SHELF",
        asset_url="sh3d/lucapresidente_mensolaciliegio.glb",
        name_en="Floating Wall Shelf",
        name_hi="फ्लोटिंग शेल्फ",
        category="storage",
        sub_category="floating_shelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1020, height_mm=340, depth_mm=200),
        price_inr=4500,
        build_price_inr=2800,
        materials=['wood_engineered'],
        tags=['shelf', 'storage', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "lamp": CatalogItem(
        sku="DINING-KEEPER-LAMP",
        asset_url="sh3d/contributions_lampehalogene.glb",
        name_en="Floor Lamp",
        name_hi="फ़र्श लैंप",
        category="lighting",
        sub_category="lamp",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=313, height_mm=1800, depth_mm=689),
        price_inr=4500,
        build_price_inr=None,
        materials=['metal', 'fabric_shade'],
        tags=['lighting', 'floor_lamp', 'ambient', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.5,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "pendant_light": CatalogItem(
        sku="DINING-KEEPER-PENDANT_LIGHT",
        asset_url="sh3d/scopia_chandelier_lamp.glb",
        name_en="Pendant Ceiling Light",
        name_hi="पेंडेंट लाइट",
        category="lighting",
        sub_category="pendant_light",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1306, height_mm=1744, depth_mm=1306),
        price_inr=7500,
        build_price_inr=None,
        materials=['metal', 'glass'],
        tags=['lighting', 'pendant', 'ceiling', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.4,
        front_clearance_mm=0,
        placement_type="ceiling",
    ),
    "mirror": CatalogItem(
        sku="DINING-KEEPER-MIRROR",
        asset_url="sh3d/contributions_mirror.glb",
        name_en="Wall Mirror",
        name_hi="दीवार दर्पण",
        category="decor",
        sub_category="mirror",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=400, height_mm=400, depth_mm=5),
        price_inr=3500,
        build_price_inr=None,
        materials=['glass', 'wood_frame'],
        tags=['mirror', 'decor', 'wall_mounted', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.1,
        front_clearance_mm=600,
        placement_type="wall",
    ),
    "wall_art": CatalogItem(
        sku="DINING-KEEPER-WALL_ART",
        asset_url="sh3d/contributions_frame3verticalsummerphotos.glb",
        name_en="Framed Wall Art",
        name_hi="दीवार चित्र",
        category="decor",
        sub_category="wall_art",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=525, height_mm=254, depth_mm=30),
        price_inr=4500,
        build_price_inr=None,
        materials=['paper', 'wood_frame'],
        tags=['art', 'decor', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "rug": CatalogItem(
        sku="DINING-KEEPER-RUG",
        asset_url="sh3d/katorlegaz_oriental_rug.glb",
        name_en="Hand-Knotted Rug",
        name_hi="कालीन",
        category="decor",
        sub_category="rug",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1858, height_mm=25, depth_mm=2577),
        price_inr=14000,
        build_price_inr=None,
        materials=['wool'],
        tags=['rug', 'decor', 'floor', 'anchor', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.95,
        front_clearance_mm=0,
        placement_type="floor",
    ),
}
