"""Auto-generated curated menu. DO NOT EDIT BY HAND.
Run scripts/generate_preset_catalogs.py to regenerate.

Menu: dining_gathering  (room_type=dining, philosophy=gathering)
Shared by both presets of this philosophy (variant 0 and variant 1).
Sub_categories curated in menus.py; geometry from curated_manifest.json;
pricing carried from hero_catalog.py."""
from __future__ import annotations

from app.domain.catalog.model import CatalogItem
from app.schemas.state import Dimensions, RoomType

CATALOG: dict[str, CatalogItem] = {
    "dining_table": CatalogItem(
        sku="DINING-GATHERING-DINING_TABLE",
        asset_url="sh3d/blendswap_cc_by_table.glb",
        name_en="4-Seater Dining Table",
        name_hi="चार-सीट डाइनिंग टेबल",
        category="table",
        sub_category="dining_table",
        rooms=[RoomType.LIVING, RoomType.DINING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1443, height_mm=724, depth_mm=934),
        price_inr=22000,
        build_price_inr=14000,
        materials=['wood_teak'],
        tags=['dining_table', 'table', 'dining', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=800,
        placement_type="floor",
    ),
    "dining_chair": CatalogItem(
        sku="DINING-GATHERING-DINING_CHAIR",
        asset_url="sh3d/scopia_plastic_chair.glb",
        name_en="Dining Chair",
        name_hi="डाइनिंग कुर्सी",
        category="seating",
        sub_category="dining_chair",
        rooms=[RoomType.LIVING, RoomType.DINING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=483, height_mm=965, depth_mm=557),
        price_inr=4500,
        build_price_inr=2800,
        materials=['wood_teak', 'fabric'],
        tags=['chair', 'dining_chair', 'dining', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bench": CatalogItem(
        sku="DINING-GATHERING-BENCH",
        asset_url="sh3d/katorlegaz_bench.glb",
        name_en="Upholstered Bench",
        name_hi="गद्देदार बेंच",
        category="seating",
        sub_category="bench",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1182, height_mm=450, depth_mm=452),
        price_inr=8000,
        build_price_inr=5000,
        materials=['fabric', 'wood_frame'],
        tags=['bench', 'seating', 'entry', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.85,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "accent_chair": CatalogItem(
        sku="DINING-GATHERING-ACCENT_CHAIR",
        asset_url="sh3d/blendswap_cc_0_modernarmchair.glb",
        name_en="Accent Chair",
        name_hi="उच्चारण कुर्सी",
        category="seating",
        sub_category="accent_chair",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=773, height_mm=865, depth_mm=849),
        price_inr=9000,
        build_price_inr=5800,
        materials=['fabric', 'wood_frame'],
        tags=['chair', 'seating', 'accent', 'formal', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.8,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "sideboard": CatalogItem(
        sku="DINING-GATHERING-SIDEBOARD",
        asset_url="sh3d/lucapresidente_credenza.glb",
        name_en="Sideboard / Buffet",
        name_hi="साइडबोर्ड",
        category="storage",
        sub_category="sideboard",
        rooms=[RoomType.LIVING, RoomType.DINING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1660, height_mm=780, depth_mm=500),
        price_inr=16000,
        build_price_inr=10000,
        materials=['wood_engineered', 'laminate'],
        tags=['sideboard', 'buffet', 'storage', 'dining', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.65,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "cabinet": CatalogItem(
        sku="DINING-GATHERING-CABINET",
        asset_url="sh3d/contributions_glassdoorcabinet.glb",
        name_en="Storage Cabinet",
        name_hi="अलमारी",
        category="storage",
        sub_category="cabinet",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=745, height_mm=1500, depth_mm=455),
        price_inr=13500,
        build_price_inr=8500,
        materials=['wood_engineered', 'laminate'],
        tags=['storage', 'cabinet', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "lamp": CatalogItem(
        sku="DINING-GATHERING-LAMP",
        asset_url="sh3d/contributions_lampehalogene.glb",
        name_en="Floor Lamp",
        name_hi="फ़र्श लैंप",
        category="lighting",
        sub_category="lamp",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=313, height_mm=1800, depth_mm=689),
        price_inr=4500,
        build_price_inr=None,
        materials=['metal', 'fabric_shade'],
        tags=['lighting', 'floor_lamp', 'ambient', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.5,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "pendant_light": CatalogItem(
        sku="DINING-GATHERING-PENDANT_LIGHT",
        asset_url="sh3d/contributions_lustreboule.glb",
        name_en="Pendant Ceiling Light",
        name_hi="पेंडेंट लाइट",
        category="lighting",
        sub_category="pendant_light",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=300, height_mm=676, depth_mm=300),
        price_inr=7500,
        build_price_inr=None,
        materials=['metal', 'glass'],
        tags=['lighting', 'pendant', 'ceiling', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.4,
        front_clearance_mm=0,
        placement_type="ceiling",
    ),
    "mirror": CatalogItem(
        sku="DINING-GATHERING-MIRROR",
        asset_url="sh3d/contributions_ovalmirror.glb",
        name_en="Wall Mirror",
        name_hi="दीवार दर्पण",
        category="decor",
        sub_category="mirror",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=550, height_mm=1050, depth_mm=10),
        price_inr=3500,
        build_price_inr=None,
        materials=['glass', 'wood_frame'],
        tags=['mirror', 'decor', 'wall_mounted', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.1,
        front_clearance_mm=600,
        placement_type="wall",
    ),
    "wall_art": CatalogItem(
        sku="DINING-GATHERING-WALL_ART",
        asset_url="sh3d/scopia_frame1.glb",
        name_en="Framed Wall Art",
        name_hi="दीवार चित्र",
        category="decor",
        sub_category="wall_art",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=145, height_mm=196, depth_mm=145),
        price_inr=4500,
        build_price_inr=None,
        materials=['paper', 'wood_frame'],
        tags=['art', 'decor', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "rug": CatalogItem(
        sku="DINING-GATHERING-RUG",
        asset_url="sh3d/katorlegaz_oriental_rug.glb",
        name_en="Hand-Knotted Rug",
        name_hi="कालीन",
        category="decor",
        sub_category="rug",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1858, height_mm=25, depth_mm=2577),
        price_inr=14000,
        build_price_inr=None,
        materials=['wool'],
        tags=['rug', 'decor', 'floor', 'anchor', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.95,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "plant": CatalogItem(
        sku="DINING-GATHERING-PLANT",
        asset_url="sh3d/blendswap_cc_0_decorativeplant.glb",
        name_en="Potted Floor Plant",
        name_hi="पौधा",
        category="decor",
        sub_category="plant",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=559, height_mm=1031, depth_mm=602),
        price_inr=2800,
        build_price_inr=None,
        materials=['ceramic', 'foliage'],
        tags=['plant', 'decor', 'softness', 'prana', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.9,
        front_clearance_mm=200,
        placement_type="floor",
    ),
}
