"""Auto-generated curated menu. DO NOT EDIT BY HAND.
Run scripts/generate_preset_catalogs.py to regenerate.

Menu: living_keeper  (room_type=living, philosophy=keeper)
Shared by both presets of this philosophy (variant 0 and variant 1).
Sub_categories curated in menus.py; geometry from curated_manifest.json;
pricing carried from hero_catalog.py."""
from __future__ import annotations

from app.domain.catalog.model import CatalogItem
from app.schemas.state import Dimensions, RoomType

CATALOG: dict[str, CatalogItem] = {
    "sofa": CatalogItem(
        sku="LIVING-KEEPER-SOFA",
        asset_url="sh3d/blendswap_cc_0_winchestersofa.glb",
        name_en="Three-seat Sofa",
        name_hi="तीन-सीट सोफा",
        category="seating",
        sub_category="sofa",
        rooms=[RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=2319, height_mm=804, depth_mm=938),
        price_inr=42000,
        build_price_inr=26000,
        materials=['fabric', 'wood_frame'],
        tags=['sofa', 'seating', 'three_seat', 'designer', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.85,
        front_clearance_mm=900,
        placement_type="floor",
    ),
    "sofa_2seat": CatalogItem(
        sku="LIVING-KEEPER-SOFA_2SEAT",
        asset_url="sh3d/scopia_beige_sofa_2seats.glb",
        name_en="Two-seat Sofa",
        name_hi="दो-सीट सोफा",
        category="seating",
        sub_category="sofa_2seat",
        rooms=[RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1589, height_mm=866, depth_mm=735),
        price_inr=26000,
        build_price_inr=16000,
        materials=['fabric', 'wood_frame'],
        tags=['sofa', 'seating', 'two_seat', 'compact', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.85,
        front_clearance_mm=900,
        placement_type="floor",
    ),
    "accent_chair": CatalogItem(
        sku="LIVING-KEEPER-ACCENT_CHAIR",
        asset_url="sh3d/scopia_armchair2.glb",
        name_en="Accent Chair",
        name_hi="उच्चारण कुर्सी",
        category="seating",
        sub_category="accent_chair",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=728, height_mm=970, depth_mm=812),
        price_inr=9000,
        build_price_inr=5800,
        materials=['fabric', 'wood_frame'],
        tags=['chair', 'seating', 'accent', 'formal', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.8,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "lounge_chair": CatalogItem(
        sku="LIVING-KEEPER-LOUNGE_CHAIR",
        asset_url="sh3d/katorlegaz_mid_century_chair.glb",
        name_en="Lounge Armchair",
        name_hi="आराम कुर्सी",
        category="seating",
        sub_category="lounge_chair",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=735, height_mm=800, depth_mm=844),
        price_inr=14000,
        build_price_inr=9000,
        materials=['fabric', 'wood_frame'],
        tags=['chair', 'seating', 'armchair', 'accent', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.8,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "pouffe": CatalogItem(
        sku="LIVING-KEEPER-POUFFE",
        asset_url="sh3d/contributions_stool_small.glb",
        name_en="Round Pouffe",
        name_hi="पूफ",
        category="seating",
        sub_category="pouffe",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=300, height_mm=450, depth_mm=300),
        price_inr=3500,
        build_price_inr=2200,
        materials=['fabric'],
        tags=['pouffe', 'seating', 'floor', 'casual', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.9,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bench": CatalogItem(
        sku="LIVING-KEEPER-BENCH",
        asset_url="sh3d/blendswap_cc_0_bench.glb",
        name_en="Upholstered Bench",
        name_hi="गद्देदार बेंच",
        category="seating",
        sub_category="bench",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1701, height_mm=508, depth_mm=459),
        price_inr=8000,
        build_price_inr=5000,
        materials=['fabric', 'wood_frame'],
        tags=['bench', 'seating', 'entry', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.85,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "coffee_table": CatalogItem(
        sku="LIVING-KEEPER-COFFEE_TABLE",
        asset_url="sh3d/contributions_coffeetable.glb",
        name_en="Coffee Table",
        name_hi="सेंटर टेबल",
        category="table",
        sub_category="coffee_table",
        rooms=[RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1170, height_mm=440, depth_mm=490),
        price_inr=9500,
        build_price_inr=6200,
        materials=['wood_teak'],
        tags=['table', 'coffee_table', 'centre_table', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "side_table": CatalogItem(
        sku="LIVING-KEEPER-SIDE_TABLE",
        asset_url="sh3d/blendswap_cc_0_bedsidetable2.glb",
        name_en="Side Table with Drawer",
        name_hi="साइड टेबल",
        category="table",
        sub_category="side_table",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=486, height_mm=454, depth_mm=481),
        price_inr=4500,
        build_price_inr=2900,
        materials=['wood_teak'],
        tags=['table', 'side_table', 'nightstand', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "tv_unit": CatalogItem(
        sku="LIVING-KEEPER-TV_UNIT",
        asset_url="sh3d/blendswap_cc_0_televisioncabinet.glb",
        name_en="TV Console with Storage",
        name_hi="टीवी यूनिट",
        category="tv_unit",
        sub_category="tv_unit",
        rooms=[RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1354, height_mm=1600, depth_mm=693),
        price_inr=16000,
        build_price_inr=10000,
        materials=['wood_engineered', 'laminate'],
        tags=['tv_unit', 'media', 'storage', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=1800,
        placement_type="floor",
    ),
    "bookshelf": CatalogItem(
        sku="LIVING-KEEPER-BOOKSHELF",
        asset_url="sh3d/contributions_meublehifihaut.glb",
        name_en="Open Bookshelf",
        name_hi="किताबों की अलमारी",
        category="storage",
        sub_category="bookshelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1559, height_mm=1830, depth_mm=414),
        price_inr=18000,
        build_price_inr=11500,
        materials=['wood_engineered'],
        tags=['storage', 'bookshelf', 'display', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "sideboard": CatalogItem(
        sku="LIVING-KEEPER-SIDEBOARD",
        asset_url="sh3d/lucapresidente_credenza.glb",
        name_en="Sideboard / Buffet",
        name_hi="साइडबोर्ड",
        category="storage",
        sub_category="sideboard",
        rooms=[RoomType.LIVING, RoomType.DINING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1660, height_mm=780, depth_mm=500),
        price_inr=16000,
        build_price_inr=10000,
        materials=['wood_engineered', 'laminate'],
        tags=['sideboard', 'buffet', 'storage', 'dining', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.65,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "cabinet": CatalogItem(
        sku="LIVING-KEEPER-CABINET",
        asset_url="sh3d/katorlegaz_filing_cabinet.glb",
        name_en="Storage Cabinet",
        name_hi="अलमारी",
        category="storage",
        sub_category="cabinet",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=386, height_mm=600, depth_mm=526),
        price_inr=13500,
        build_price_inr=8500,
        materials=['wood_engineered', 'laminate'],
        tags=['storage', 'cabinet', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "chest": CatalogItem(
        sku="LIVING-KEEPER-CHEST",
        asset_url="sh3d/blendswap_cc_by_chest.glb",
        name_en="Chest of Drawers",
        name_hi="दराज़ की अलमारी",
        category="storage",
        sub_category="chest",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1435, height_mm=820, depth_mm=536),
        price_inr=16500,
        build_price_inr=10500,
        materials=['wood_engineered'],
        tags=['storage', 'drawers', 'chest', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "floating_shelf": CatalogItem(
        sku="LIVING-KEEPER-FLOATING_SHELF",
        asset_url="sh3d/lucapresidente_mensolaciliegio.glb",
        name_en="Floating Wall Shelf",
        name_hi="फ्लोटिंग शेल्फ",
        category="storage",
        sub_category="floating_shelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1020, height_mm=340, depth_mm=200),
        price_inr=4500,
        build_price_inr=2800,
        materials=['wood_engineered'],
        tags=['shelf', 'storage', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "lamp": CatalogItem(
        sku="LIVING-KEEPER-LAMP",
        asset_url="sh3d/contributions_lampehalogene.glb",
        name_en="Floor Lamp",
        name_hi="फ़र्श लैंप",
        category="lighting",
        sub_category="lamp",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=313, height_mm=1800, depth_mm=689),
        price_inr=4500,
        build_price_inr=None,
        materials=['metal', 'fabric_shade'],
        tags=['lighting', 'floor_lamp', 'ambient', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.5,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "desk_lamp": CatalogItem(
        sku="LIVING-KEEPER-DESK_LAMP",
        asset_url="sh3d/scopia_desk_lamp2.glb",
        name_en="Task Desk Lamp",
        name_hi="डेस्क लैंप",
        category="lighting",
        sub_category="desk_lamp",
        rooms=[RoomType.STUDY, RoomType.BEDROOM, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=225, height_mm=400, depth_mm=417),
        price_inr=2200,
        build_price_inr=None,
        materials=['metal'],
        tags=['lighting', 'desk_lamp', 'task', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.4,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "mirror": CatalogItem(
        sku="LIVING-KEEPER-MIRROR",
        asset_url="sh3d/contributions_mirror.glb",
        name_en="Wall Mirror",
        name_hi="दीवार दर्पण",
        category="decor",
        sub_category="mirror",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=400, height_mm=400, depth_mm=5),
        price_inr=3500,
        build_price_inr=None,
        materials=['glass', 'wood_frame'],
        tags=['mirror', 'decor', 'wall_mounted', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.1,
        front_clearance_mm=600,
        placement_type="wall",
    ),
    "wall_art": CatalogItem(
        sku="LIVING-KEEPER-WALL_ART",
        asset_url="sh3d/contributions_frame3verticalsummerphotos.glb",
        name_en="Framed Wall Art",
        name_hi="दीवार चित्र",
        category="decor",
        sub_category="wall_art",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=525, height_mm=254, depth_mm=30),
        price_inr=4500,
        build_price_inr=None,
        materials=['paper', 'wood_frame'],
        tags=['art', 'decor', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "rug": CatalogItem(
        sku="LIVING-KEEPER-RUG",
        asset_url="sh3d/katorlegaz_oriental_rug.glb",
        name_en="Hand-Knotted Rug",
        name_hi="कालीन",
        category="decor",
        sub_category="rug",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1858, height_mm=25, depth_mm=2577),
        price_inr=14000,
        build_price_inr=None,
        materials=['wool'],
        tags=['rug', 'decor', 'floor', 'anchor', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.95,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "plant": CatalogItem(
        sku="LIVING-KEEPER-PLANT",
        asset_url="sh3d/scopia_maceta.glb",
        name_en="Potted Floor Plant",
        name_hi="पौधा",
        category="decor",
        sub_category="plant",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=590, height_mm=580, depth_mm=650),
        price_inr=2800,
        build_price_inr=None,
        materials=['ceramic', 'foliage'],
        tags=['plant', 'decor', 'softness', 'prana', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.9,
        front_clearance_mm=200,
        placement_type="floor",
    ),
}
