"""Auto-generated curated menu. DO NOT EDIT BY HAND.
Run scripts/generate_preset_catalogs.py to regenerate.

Menu: study_breath  (room_type=study, philosophy=breath)
Shared by both presets of this philosophy (variant 0 and variant 1).
Sub_categories curated in menus.py; geometry from curated_manifest.json;
pricing carried from hero_catalog.py."""
from __future__ import annotations

from app.domain.catalog.model import CatalogItem
from app.schemas.state import Dimensions, RoomType

CATALOG: dict[str, CatalogItem] = {
    "desk": CatalogItem(
        sku="STUDY-BREATH-DESK",
        asset_url="sh3d/blendswap_cc_by_biurko3.glb",
        name_en="Work Desk",
        name_hi="अध्ययन मेज़",
        category="table",
        sub_category="desk",
        rooms=[RoomType.BEDROOM, RoomType.STUDY, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1201, height_mm=720, depth_mm=602),
        price_inr=14000,
        build_price_inr=9000,
        materials=['wood_engineered'],
        tags=['desk', 'table', 'study', 'wfh', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.55,
        front_clearance_mm=1000,
        placement_type="floor",
    ),
    "desk_chair": CatalogItem(
        sku="STUDY-BREATH-DESK_CHAIR",
        asset_url="sh3d/contributions_officechair2.glb",
        name_en="Task Chair",
        name_hi="कार्य कुर्सी",
        category="seating",
        sub_category="desk_chair",
        rooms=[RoomType.BEDROOM, RoomType.STUDY, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=629, height_mm=1015, depth_mm=688),
        price_inr=9000,
        build_price_inr=None,
        materials=['mesh', 'metal'],
        tags=['chair', 'office', 'task', 'wfh', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bookshelf": CatalogItem(
        sku="STUDY-BREATH-BOOKSHELF",
        asset_url="sh3d/contributions_bookcase.glb",
        name_en="Open Bookshelf",
        name_hi="किताबों की अलमारी",
        category="storage",
        sub_category="bookshelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1825, height_mm=1500, depth_mm=313),
        price_inr=18000,
        build_price_inr=11500,
        materials=['wood_engineered'],
        tags=['storage', 'bookshelf', 'display', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "floating_shelf": CatalogItem(
        sku="STUDY-BREATH-FLOATING_SHELF",
        asset_url="sh3d/lucapresidente_mensolaacero.glb",
        name_en="Floating Wall Shelf",
        name_hi="फ्लोटिंग शेल्फ",
        category="storage",
        sub_category="floating_shelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=600, height_mm=50, depth_mm=200),
        price_inr=4500,
        build_price_inr=2800,
        materials=['wood_engineered'],
        tags=['shelf', 'storage', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "side_table": CatalogItem(
        sku="STUDY-BREATH-SIDE_TABLE",
        asset_url="sh3d/lucapresidente_comodinoazzurro.glb",
        name_en="Side Table with Drawer",
        name_hi="साइड टेबल",
        category="table",
        sub_category="side_table",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=500, height_mm=480, depth_mm=425),
        price_inr=4500,
        build_price_inr=2900,
        materials=['wood_teak'],
        tags=['table', 'side_table', 'nightstand', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "lamp": CatalogItem(
        sku="STUDY-BREATH-LAMP",
        asset_url="sh3d/contributions_lampehalogene.glb",
        name_en="Floor Lamp",
        name_hi="फ़र्श लैंप",
        category="lighting",
        sub_category="lamp",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=313, height_mm=1800, depth_mm=689),
        price_inr=4500,
        build_price_inr=None,
        materials=['metal', 'fabric_shade'],
        tags=['lighting', 'floor_lamp', 'ambient', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.5,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "desk_lamp": CatalogItem(
        sku="STUDY-BREATH-DESK_LAMP",
        asset_url="sh3d/scopia_desk_lamp1.glb",
        name_en="Task Desk Lamp",
        name_hi="डेस्क लैंप",
        category="lighting",
        sub_category="desk_lamp",
        rooms=[RoomType.STUDY, RoomType.BEDROOM, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=137, height_mm=450, depth_mm=342),
        price_inr=2200,
        build_price_inr=None,
        materials=['metal'],
        tags=['lighting', 'desk_lamp', 'task', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.4,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "wall_art": CatalogItem(
        sku="STUDY-BREATH-WALL_ART",
        asset_url="sh3d/scopia_frame2.glb",
        name_en="Framed Wall Art",
        name_hi="दीवार चित्र",
        category="decor",
        sub_category="wall_art",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=145, height_mm=199, depth_mm=145),
        price_inr=4500,
        build_price_inr=None,
        materials=['paper', 'wood_frame'],
        tags=['art', 'decor', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "plant": CatalogItem(
        sku="STUDY-BREATH-PLANT",
        asset_url="sh3d/scopia_ficus.glb",
        name_en="Potted Floor Plant",
        name_hi="पौधा",
        category="decor",
        sub_category="plant",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=425, height_mm=824, depth_mm=415),
        price_inr=2800,
        build_price_inr=None,
        materials=['ceramic', 'foliage'],
        tags=['plant', 'decor', 'softness', 'prana', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.9,
        front_clearance_mm=200,
        placement_type="floor",
    ),
}
