"""Auto-generated curated menu. DO NOT EDIT BY HAND.
Run scripts/generate_preset_catalogs.py to regenerate.

Menu: study_gathering  (room_type=study, philosophy=gathering)
Shared by both presets of this philosophy (variant 0 and variant 1).
Sub_categories curated in menus.py; geometry from curated_manifest.json;
pricing carried from hero_catalog.py."""
from __future__ import annotations

from app.domain.catalog.model import CatalogItem
from app.schemas.state import Dimensions, RoomType

CATALOG: dict[str, CatalogItem] = {
    "desk": CatalogItem(
        sku="STUDY-GATHERING-DESK",
        asset_url="sh3d/contributions_bureau3.glb",
        name_en="Work Desk",
        name_hi="अध्ययन मेज़",
        category="table",
        sub_category="desk",
        rooms=[RoomType.BEDROOM, RoomType.STUDY, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1200, height_mm=725, depth_mm=590),
        price_inr=14000,
        build_price_inr=9000,
        materials=['wood_engineered'],
        tags=['desk', 'table', 'study', 'wfh', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.55,
        front_clearance_mm=1000,
        placement_type="floor",
    ),
    "desk_chair": CatalogItem(
        sku="STUDY-GATHERING-DESK_CHAIR",
        asset_url="sh3d/contributions_officechair.glb",
        name_en="Task Chair",
        name_hi="कार्य कुर्सी",
        category="seating",
        sub_category="desk_chair",
        rooms=[RoomType.BEDROOM, RoomType.STUDY, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=626, height_mm=873, depth_mm=597),
        price_inr=9000,
        build_price_inr=None,
        materials=['mesh', 'metal'],
        tags=['chair', 'office', 'task', 'wfh', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "bookshelf": CatalogItem(
        sku="STUDY-GATHERING-BOOKSHELF",
        asset_url="sh3d/blendswap_cc_by_bookcase.glb",
        name_en="Open Bookshelf",
        name_hi="किताबों की अलमारी",
        category="storage",
        sub_category="bookshelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1664, height_mm=1864, depth_mm=331),
        price_inr=18000,
        build_price_inr=11500,
        materials=['wood_engineered'],
        tags=['storage', 'bookshelf', 'display', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "cabinet": CatalogItem(
        sku="STUDY-GATHERING-CABINET",
        asset_url="sh3d/contributions_glassdoorcabinet.glb",
        name_en="Storage Cabinet",
        name_hi="अलमारी",
        category="storage",
        sub_category="cabinet",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=745, height_mm=1500, depth_mm=455),
        price_inr=13500,
        build_price_inr=8500,
        materials=['wood_engineered', 'laminate'],
        tags=['storage', 'cabinet', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "floating_shelf": CatalogItem(
        sku="STUDY-GATHERING-FLOATING_SHELF",
        asset_url="sh3d/lucapresidente_mensolacurvaacero.glb",
        name_en="Floating Wall Shelf",
        name_hi="फ्लोटिंग शेल्फ",
        category="storage",
        sub_category="floating_shelf",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=400, height_mm=30, depth_mm=400),
        price_inr=4500,
        build_price_inr=2800,
        materials=['wood_engineered'],
        tags=['shelf', 'storage', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.7,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "accent_chair": CatalogItem(
        sku="STUDY-GATHERING-ACCENT_CHAIR",
        asset_url="sh3d/blendswap_cc_0_modernarmchair.glb",
        name_en="Accent Chair",
        name_hi="उच्चारण कुर्सी",
        category="seating",
        sub_category="accent_chair",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=773, height_mm=865, depth_mm=849),
        price_inr=9000,
        build_price_inr=5800,
        materials=['fabric', 'wood_frame'],
        tags=['chair', 'seating', 'accent', 'formal', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.8,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "lounge_chair": CatalogItem(
        sku="STUDY-GATHERING-LOUNGE_CHAIR",
        asset_url="sh3d/blendswap_cc_by_fotel.glb",
        name_en="Lounge Armchair",
        name_hi="आराम कुर्सी",
        category="seating",
        sub_category="lounge_chair",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=735, height_mm=697, depth_mm=611),
        price_inr=14000,
        build_price_inr=9000,
        materials=['fabric', 'wood_frame'],
        tags=['chair', 'seating', 'armchair', 'accent', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.8,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "pouffe": CatalogItem(
        sku="STUDY-GATHERING-POUFFE",
        asset_url="sh3d/blendswap_cc_by_green_stool.glb",
        name_en="Round Pouffe",
        name_hi="पूफ",
        category="seating",
        sub_category="pouffe",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=429, height_mm=460, depth_mm=429),
        price_inr=3500,
        build_price_inr=2200,
        materials=['fabric'],
        tags=['pouffe', 'seating', 'floor', 'casual', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.9,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "side_table": CatalogItem(
        sku="STUDY-GATHERING-SIDE_TABLE",
        asset_url="sh3d/blendswap_cc_by_bedsidetable.glb",
        name_en="Side Table with Drawer",
        name_hi="साइड टेबल",
        category="table",
        sub_category="side_table",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=500, height_mm=480, depth_mm=414),
        price_inr=4500,
        build_price_inr=2900,
        materials=['wood_teak'],
        tags=['table', 'side_table', 'nightstand', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "lamp": CatalogItem(
        sku="STUDY-GATHERING-LAMP",
        asset_url="sh3d/contributions_lampehalogene.glb",
        name_en="Floor Lamp",
        name_hi="फ़र्श लैंप",
        category="lighting",
        sub_category="lamp",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=313, height_mm=1800, depth_mm=689),
        price_inr=4500,
        build_price_inr=None,
        materials=['metal', 'fabric_shade'],
        tags=['lighting', 'floor_lamp', 'ambient', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.5,
        front_clearance_mm=600,
        placement_type="floor",
    ),
    "desk_lamp": CatalogItem(
        sku="STUDY-GATHERING-DESK_LAMP",
        asset_url="sh3d/blendswap_cc_0_desklamp.glb",
        name_en="Task Desk Lamp",
        name_hi="डेस्क लैंप",
        category="lighting",
        sub_category="desk_lamp",
        rooms=[RoomType.STUDY, RoomType.BEDROOM, RoomType.LIVING],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=244, height_mm=400, depth_mm=244),
        price_inr=2200,
        build_price_inr=None,
        materials=['metal'],
        tags=['lighting', 'desk_lamp', 'task', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.4,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "wall_art": CatalogItem(
        sku="STUDY-GATHERING-WALL_ART",
        asset_url="sh3d/scopia_frame1.glb",
        name_en="Framed Wall Art",
        name_hi="दीवार चित्र",
        category="decor",
        sub_category="wall_art",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=145, height_mm=196, depth_mm=145),
        price_inr=4500,
        build_price_inr=None,
        materials=['paper', 'wood_frame'],
        tags=['art', 'decor', 'wall', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.6,
        front_clearance_mm=0,
        placement_type="wall",
    ),
    "rug": CatalogItem(
        sku="STUDY-GATHERING-RUG",
        asset_url="sh3d/katorlegaz_oriental_rug.glb",
        name_en="Hand-Knotted Rug",
        name_hi="कालीन",
        category="decor",
        sub_category="rug",
        rooms=[RoomType.LIVING, RoomType.BEDROOM],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=1858, height_mm=25, depth_mm=2577),
        price_inr=14000,
        build_price_inr=None,
        materials=['wool'],
        tags=['rug', 'decor', 'floor', 'anchor', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.95,
        front_clearance_mm=0,
        placement_type="floor",
    ),
    "plant": CatalogItem(
        sku="STUDY-GATHERING-PLANT",
        asset_url="sh3d/blendswap_cc_0_decorativeplant.glb",
        name_en="Potted Floor Plant",
        name_hi="पौधा",
        category="decor",
        sub_category="plant",
        rooms=[RoomType.LIVING, RoomType.BEDROOM, RoomType.DINING, RoomType.STUDY],
        vibes=[],  # vibe-agnostic for now; preset philosophy drives selection
        dimensions=Dimensions(width_mm=559, height_mm=1031, depth_mm=602),
        price_inr=2800,
        build_price_inr=None,
        materials=['ceramic', 'foliage'],
        tags=['plant', 'decor', 'softness', 'prana', 'curated'],
        tint_hex=None,
        size_label=None,
        material_label=None,
        finish_label=None,
        roughness_hint=0.9,
        front_clearance_mm=200,
        placement_type="floor",
    ),
}
